title: ALCaaat
description: 随便写点东西
url: "https://ALCaaat.github.io"
baseurl: ""

theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
permalink: /:year/:month/:day/:title/

exclude:
  - README.md
